export const projects = [
  {
    title: 'My CodePen',
    description: "My CodePen where I have some CSS effects and other Microservices.",
      image: '/images/3.png',
      tags: ['CSS', 'MicroServices'],
    source: 'https://codepen.io/coderkael',
    visit: 'https://codepen.io/coderkael',
    id: 0,
  },
  {
    title: 'ECOM Website',
    description: "Using NextJs with Javascript and SanityDb to create a FullStack ecommerce website with Stripe payments.",
      image: '/images/1.png',
      tags: ['NextJs', 'Sanity', 'React', 'CSS', 'JavaScript', 'Stripe'],
    source: 'https://github.com/CoderKael/ecom',
    visit: 'https://ecomfinal.vercel.app',
    id: 1,
  },
  {
    title: 'Social Media Clone',
    description:"Using NextJs with TypeScript, Tailwind and SanityDb to create a TikTok clone social media with Google OAuth accounts.",
    image: '/images/2.png',
    tags: ['TypeScript', 'Tailwind', 'Zustand', 'NextJs', 'Sanity'],
    source: 'https://github.com/CoderKael/TikTok-Clone',
    visit: 'https://tik-tok-clonefinal.vercel.app',
    id: 2,
  },
  {
    title: 'GraphCMS Blog',
    description: "Blog using NextJs, GraphCMS, Tailwind (Not yet deployed).",
      image: '/images/4.png',
      tags: ['Tailwind', 'JavaScript', 'NextJs', 'GraphCMS'],
    source: 'https://github.com/CoderKael/graphcmsBlog',
    visit: '/',
    id: 3,
  },
  {
    title: 'Metaversus',
    description: "Modern website with animations using framer-motion.",
      image: '/images/5.png',
      tags: ['Tailwind', 'JavaScript', 'NextJs', 'Framer-Motion'],
    source: 'https://github.com/CoderKael/metaversus',
    visit: 'https://metaversus-swart.vercel.app',
    id: 4,
  },
  {
    title: 'Share Me',
    description: "Image sharing social media.",
      image: '/images/6.png',
      tags: ['Tailwind', 'JavaScript', 'ReactJs', 'Sanity', 'GoogleOAuth'],
    source: '/',
    visit: 'https://sharemefinal.netlify.app',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2020, text: 'Started my coding journey', },
  { year: 2021, text: 'Began doing unity game development', },
  { year: 2022, text: 'Began website development', },
];